//! SeaORM Entity. Generated by sea-orm-codegen 0.9.2

pub use super::other_table_a::Entity as OtherTableA;
pub use super::other_table_b::Entity as OtherTableB;
pub use super::table_a::Entity as TableA;
pub use super::table_b::Entity as TableB;
